### ISSUE TITLE
Memory leak in the RoundRobin balancer

### ISSUE THREAD

**Issue by elwinar** [olivere/balancers#1]
I haven't investigated the details, but the RoundRobin balancer seems to leak memory.

I found out by using it with a service that needed to send big payloads (like, multi megabytes payloads) at recurring intervals. Somehow, removing the RoundRobin and using a randomly built URL solved the problem, so I expected the balancer's logic to be faulty somewhere.

I'll take the time to do a working example of this later to demonstrate the problem.

**Comment by olivere** [comment]
Hmm... okay. First thing I always check in this situation is if the HTTP response body is closed.

Although this repository is just an experiment, I still want it to work. Thanks for sending a reproducible test case.

**Comment by elwinar** [comment]
Didin't had the time to do it this week-end… hold on, I'll have two free hours one day or another :D

**Comment by olivere** [comment]
Sure. Appreciate your time.

**Comment by satish5** [comment]
Hi, this is something that I'd like to try out in a production environment. Did you manage to get to the bottom of the memory leak?

**Comment by olivere** [comment]
I couldn't find a memory leak. However, there was an issue with copying a `sync.Mutex`. Let me know if this still doesn't solve the issue and I'll reinvestigate.

**Comment by olivere** [comment]
It has hopefully been fixed by @D3luxee in 1.0.1.
