### ISSUE TITLE
Balancer Documentation

### ISSUE THREAD

**Issue by Bubsavvage** [olivere/balancers#4]
There is a lack of documentation on this tool. It would be really helpful to provide usage examples both simple and advanced to help describe usage. Currently the only way to see this is via your test cases.

**Comment by olivere** [comment]
You're probably right. But, you know, I wrote this little package for fun, in my spare time, without getting paid, and gave it an MIT license. You are free to use it like you want; you can even modify it and fork it without even mentioning me anywhere. So yeah, documentation missing. But anyone using it should be able to read the code and the tests and get an idea of how it's being used. If that's not good enough for you, that's okay.

If, however, you want to help the open source movement, feel free to add documentation or write a blog post about it. I'm happy to merge PRs and link to articles describing the experiences with this library.

As for documentation. The core functionality of the package is abstracted away by the two interfaces [`balancers.Balancer`](https://github.com/olivere/balancers/blob/master/balancer.go#L6-L13) and [`balancers.Connection`](https://github.com/olivere/balancers/blob/master/connection.go#L13-L21). You can freely create your own implementation of these interfaces and use [`balancer.NewClient(...)`](https://github.com/olivere/balancers/blob/master/client.go#L10-L16) to the goal of the package: very simple HTTP-based load-balancing.

E.g. you could create a balancer that uses the least-recently-used algorithm for load-balancing. Simply add a `lru` package (again, PRs welcome) and implement `lru.Balancer` and `lru.Connection` by using something like:

```
package lru

import (
  "github.com/olivere/balancers"
)

type Balancer struct {
   ...
}

var _ balancers.Balancer = (*Balancer)(nil) // ensure compiler bails if interface is not implemented

func NewBalancer(failingErrorCodes []int, conns ...*Connection) *Balancer {
   ...
}

func (b *Balancer) Get() (balancer.Connection, error) { ... }

func (b *Balancer) Connections() []balancer.Connection { ... }

...

type Connection struct {
}

var _ balancers.Connection = (*Connection)(nil) // ensure compiler bails if interface is not implemented

func NewConnection() *Connection {
  ...
}

func (c *Connection) URL() *url.URL  { ... }
func (c *Connection) IsBroken() bool { ... }
```

Now, given that the abstractions hold, you "just" need to fill the gaps.
